language: java
#mvn: clean install test org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=1e6ab5e2e29dc5e42e4fcefc555d4210c8c1374b
#mvn: clean install -DskipTests=true
#mvn: test
